### ISSUE TITLE
I found node-multiparty have a bug

### ISSUE THREAD

**Issue by alexOnlyliu** [pillarjs/multiparty#121]
I found multiparty.Form.maxFilesSize have a bug. when two files in a form, the maxFilesSize limit have a bug.

 For example，I up two files in a form, each file size is 5,242,880, and set Form.maxFilesSize = 5,242,880 \* 2 - 1;  the reasult, two files is up Success， no limited.

   the reason : code exec node-multiparty(@4.1.2): index.js: 663:  internalFile.ws = slicer.createWriteStream({end: self.maxFilesSize - self.totalFileSize}); 

   for first files, code first exec node-multiparty(@4.1.2): index.js: 663, the self.maxFilesSize is (5,242,880 \* 2 - 1), self.totalFileSize is 0.

   for second files，code second exec node-multiparty(@4.1.2): index.js: 663, the self.maxFilesSize is (5,242,880 \* 2 - 1), self.totalFileSize is 5,094,279，but expected is  5,242,880.

 so,why did you change Form.maxFilesSize to Form.maxFileSize, limit each a file max size,not all files max size.

 For example,node-multiparty(@4.1.2): index.js: 663:  internalFile.ws = slicer.createWriteStream({end: self.maxFileSize});

**Comment by dougwilson** [comment]
Hi @alexOnlyliu I apologize for this falling off my radar for so long. Unfortunately (fortunately?) even though it seems the code flow you described still exists in the current version of this module, it seems to not be reproducible as described. I added a test following the exact replication steps you described above and it does error out as expected. This issue will close as the new test lands in `master`.
