### ISSUE TITLE
'error' emitted after 'close'

### ISSUE THREAD

**Issue by ronag** [pillarjs/multiparty#138]
This is a bit weird. When the client cancels a request, after all data has been read but before the server `res.end()` the response, then `error`  can be called after `close`.

I think the following happens
1. Client Uploads
2. Entire Request has completed
3. Server does not end the response (still processing)
4. 'close' is emitted
5. Client Cancels
6. 'error' is emitted

**Comment by dougwilson** [comment]
Yes, I see the issue as well. You're welcome to make a pull request to fix (and add a test) if you're up to it, otherwise I'll try to get around to it :)

**Comment by clivend** [comment]
+1

**Comment by emelineL** [comment]
+1

**Comment by amitguptagwl** [comment]
@dougwilson does this bug still exist?

**Comment by dougwilson** [comment]
Yes
