### ISSUE TITLE
Is a release planned?

### ISSUE THREAD

**Issue by robinbullocks4rb** [pillarjs/multiparty#156]
Hi, I'm seeing deprecation warnings for #140 (fixed in master) in our application and I'm wondering if you plan a release in the near future so this can be used?

If there's anything I can do to assist in getting a release out please let me know.

**Comment by dougwilson** [comment]
I had simply forgotten there were pending changes. I'll get the build fixed and something published to npm sometime this week perhaps.

**Comment by robinbullocks4rb** [comment]
@dougwilson, thank you, really appreciate it.

**Comment by LinusU** [comment]
@dougwilson Can we get this moving, it would be nice to not have to see a deprecation warning every time this module is used :)

Is there anything I could do btw? Or who has publishing rights to npm?

**Comment by dougwilson** [comment]
I will get everything moved around today. @LinusU I was thinking that since this module really isn't a middleware, we should probably move it into either `pillarjs` or `jshttp` and then release. Any preference?

**Comment by LinusU** [comment]
No preference from my side, thinking that it might be better suited for `pillarjs` though? :)

**Comment by dougwilson** [comment]
Yea, that was kind of where I've been leaning.

**Comment by dougwilson** [comment]
Ok, just moved it to `pillarjs/multiparty`, now to get it updated.

**Comment by dougwilson** [comment]
I can't seem to get the Coveralls integration to update the location. @andrewrk can you help? Go to https://coveralls.io/github/andrewrk/node-multiparty/settings and either (a) click the sync button and see if it updates to pillarjs/multiparty or (b) just click delete repo and then I can create it again from the new location.

**Comment by andrewrk** [comment]
I pushed the sync button and it seemed to do the trick.

**Comment by dougwilson** [comment]
Nice, @andrewrk looks like it's all syncing up now :D

**Comment by dougwilson** [comment]
Published 4.1.3 to npm, which fixes the deprecation warnings
