### ISSUE TITLE
Incompatibilty with node v6.9.5

### ISSUE THREAD

**Issue by crazyquark** [pillarjs/multiparty#162]
`function Form(options) {
  var self = this;
  stream.Writable.call(self);`

the .call() line here throws an exception if ran in a node v6.9.5 on OS X 10.11.

**Comment by dougwilson** [comment]
Hm, I can use it just fine on Node.ks 6 without error. Can you provide the complete error with stack trace and a complete app I can run which reproduces the issue? Or perhaps a PR with a fix that works for you?

**Comment by dougwilson** [comment]
I just re-ran our test suite on Travis CI on Node.js 6.9.5 and it ran without issue: https://travis-ci.org/pillarjs/multiparty/jobs/194292423

If you have any additional information, I can always re-open the issue.
