### ISSUE TITLE
Can't upload file above, 15 MB (or partially upload)

### ISSUE THREAD

**Issue by khatekar** [pillarjs/multiparty#163]
I am using "ng-file-upload": "12.2.13", "angular": "1.4.7", "node": "6.9.0", "npm": "3.10.8" and "multiparty": "4.1.2".

I imported a file of size > 20 MB, it did not show up. All the file-import POST requests get a 200 response. But the location where the file saved shows no or partially uploaded files. The file upload in 10MB chunks. No issue with the nginx max file size upload, it has already increased (15MB). My server  has multiple instances that are round-robbined. So it might be all instances gets the chunks data and have overwritten the file and saved partially to the destination
Not sure what is the issue; there are no logs in console or in the server side. 
 Is there any way using multiparty it sends/gets files persist to a single instance, instead to the multiple.

Thank you.

**Comment by dougwilson** [comment]
I'm not sure. Any insight you have on what we should change would be awesome 😊

**Comment by khatekar** [comment]
I have updated the my question description.

**Comment by dougwilson** [comment]
It looks the same reading it again. What did you add to it?

**Comment by khatekar** [comment]
I have fixed the issue. The issue is was with nginx proxy. I disabled load balancing instances for my file-import API and assigned persist connection to one instance.

Thank you.
