### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by craigvantonder** [pillarjs/multiparty#164]
Node: v7.4.0

Using [Skipper](https://github.com/balderdashy/skipper) which is using multiparty and during a file upload I received the following notice/warning message in the console:

    (node:3108) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

So I ran:

    root@node:/myApp# grep "os.tmpDir()" * -R
    node_modules/multiparty/CHANGELOG.md:* Use os.tmpDir() to get tmp directory (Andrew Kelley)
    node_modules/multiparty/README.md:   Defaults to `os.tmpDir()`.
    node_modules/multiparty/index.js:  self.uploadDir = options.uploadDir || os.tmpDir();

Not sure how this affects things currently so didn't want to make a PR but just wanted to put that out there for consideration.

**Comment by dougwilson** [comment]
That warning happens on versions below the current 4.1.3 of this module. Skipper has released a new version with 4.1.3 as it's dependency, so make sure you are running Skipper 0.8.0
