### ISSUE TITLE
Error: unsupported content-type

### ISSUE THREAD

**Issue by peacemakr** [pillarjs/multiparty#167]
I'm getting the error in subject when trying to parse a request.

I've double checked the content-type in Chrome which shows
```
Content-Type:application/x-www-form-urlencoded
```
Also, the request is a the confirmation part of a multi-part file upload. The uploaded file is PDF.

**Comment by dougwilson** [comment]
That's correct, this module does not support that content type. From the first line of the readme:

> Parse http requests with content-type multipart/form-data, also known as file uploads.
