### ISSUE TITLE
form.on('part', ...) add remember to add part.on('error', ...) for each part

### ISSUE THREAD

**Issue by ebdrup** [pillarjs/multiparty#170]
In the example with `form.on('part', ...)` it would be good to add to the docs that it's good to add a `part.on('error', ...)` for each part. If you dont want to risk `EPIPE` uncaught exceptions.

I was fighting with some edge cases and discovered this.

**Comment by dougwilson** [comment]
The docs already mention this multiple times, like

>  part  emits 'error' events! Make sure you handle them.

Can you make a PR for how to improve the docs that would satisfy you? I really don't understand how many times it has to be stated to be enough, and I thought writing it several times would be enough, but I guess not. I'm at a loss of how many more times to add it and where, so a PR would be the best way to help me understand what is necessary.

**Comment by ebdrup** [comment]
Oops, I was looking for it in the comments in the code under the `form.parse(request, [cb])` heading

**Comment by ebdrup** [comment]
Or maybe even add on error handlers in the example code.

**Comment by ebdrup** [comment]
Oh it's there. I'm on a roll of not paying attention it seems. Sorry.
