### ISSUE TITLE
README’s reference to busboy and benchmarks is confusing

### ISSUE THREAD

**Issue by binki** [pillarjs/multiparty#177]
The linked to [benchmarks](https://github.com/mscdex/dicer/wiki/Benchmarks) don’t mention [busboy](https://github.com/mscdex/busboy). The README of the npm package mentions temporary files, etc. Does multiparty transparently create temporary files instead of streaming by default or something? Could the README say what causes temporary files to be created?

I *think* that the README is recommending me use busboy instead, so I will use that then…

**Comment by dougwilson** [comment]
Under the hood of busboy is dicer, which is what you see in those benchmarks. Those are the benchmarks linked to from busboy, so you may want to file an issue there to note what dicer means in the benchmarks table.

**Comment by sant123** [comment]
`See also busboy - a faster alternative which may be worth looking into.` I agree with @binki about the recommend the library gives. Shall be still moving to Busboy? It's confusing @dougwilson :confused:

**Comment by dougwilson** [comment]
Use the nodule that works best for you.
