### ISSUE TITLE
Error - "400 - Bad Request" while file upload

### ISSUE THREAD

**Issue by Vipin1702** [pillarjs/multiparty#178]
I have created Node file API to upload files one by one and hosted on Linux machine using docker containers. Following is the sample code. It is written in Type script.  File upload API works file. **But at times it returns following error**. Please let me know, what's wrong with the code.  

**Error**
{"Version":{"Major":1,"Minor":1,"Build":-1,"Revision":-1,"MajorRevision":-1,"MinorRevision":-1},"Content":{"Headers":[{"Key":"Content-Length","Value":["36"]},{"Key":"Content-Type","Value":["text/html; charset=utf-8"]}]},"StatusCode":400,"ReasonPhrase":"Bad Request","Headers":[{"Key":"Connection","Value":["keep-alive"]},{"Key":"Access-Control-Allow-Headers","Value":["Content-Type, Authorization"]},{"Key":"Access-Control-Allow-Methods","Value":["GET,PUT,POST,DELETE"]},{"Key":"X-Kong-Upstream-Latency","Value":["12"]},{"Key":"X-Kong-Proxy-Latency","Value":["0"]},{"Key":"Date","Value":["Wed, 28 Jun 2017 06:10:00 GMT"]},{"Key":"ETag","Value":["W/\"24-/IGHYVuF0eJcMoZHAGsUM/Qz5Hw\""]},{"Key":"Server","Value":["nginx/1.11.5"]},{"Key":"Via","Value":["kong/0.10.3"]},{"Key":"X-Powered-By","Value":["Express"]}],"RequestMessage":{"Version":{"Major":1,"Minor":1,"Build":-1,"Revision":-1,"MajorRevision":-1,"MinorRevision":-1},"Content":[],"Method":{"Method":"POST"},"RequestUri":"https://hostname/upload-file/api/files/","Headers":[],"Properties":{}},"IsSuccessStatusCode":false}

**Code:**
```js
 if (fs.existsSync(filePath)) {
                const form = new multiparty.Form();
                form.parse(req, (err: any, fields: any, files: any) => {
                    if (err) {
                        logger.info(JSON.stringify(err));
                        res.status(400).send(JSON.stringify(err));
                        return;
                    }
                    res.writeHead(200, { 'content-type': 'text/plain' });
                    res.end(keyForFileStore);
                });
                form.on('file', (name: any, file: any) => {
                    logger.info('uploadFile : Controller - Upload File End for file: ' + file.originalFilename);
                    const writeStream = fs.createWriteStream(filePath + keyForFileStore);
                    fs.createReadStream(file.path).pipe(writeStream);
                    fs.unlink(file.path, (err) => {
                        logger.info('Temp file path: ' + file.path);
                        if (!fs.existsSync(file.path)) {
                            logger.info('Temp File deleted successfully');
                        } else {
                            logger.info('Temp File cloud not be deleted');
                        }
                    });
                    // fs.rename(file.path, filePath + keyForFileStore);
                });
            } else {
                res.status(400).send('File upload directory does not exist');
            }
```

**Comment by dougwilson** [comment]
Hi @Vipin1702 I looked through that error you posted, but it doesn't seem to contain what the error's message is (what you're writing to `res.send`). Can you provide that?

**Comment by dougwilson** [comment]
Closing since I never heard back.
