### ISSUE TITLE
multiparty 4.1.3 | image is not getting upload and stored in directory.

### ISSUE THREAD

**Issue by AbhijeetGiram** [pillarjs/multiparty#182]
I want to upload image and it is working fine with http. But I used self signed certificate and want to https. But image/file upload is not working. Image is not getting stored, so unable to fetch that image.

When I call upload/image api, I got response(200). But still image is not stored in directory.
Need help.

Code:
//server side
 __dirname = 'src/server';
  var form = new multiparty.Form({uploadDir: __dirname});
  form.parse(req, (err: Error, fields: any, files: any)

//client side
this.filesToUpload = <Array<File>> fileInput.target.files;
    if (this.filesToUpload[0].type === 'image/jpeg')

//network call
------WebKitFormBoundaryHEiJYOCkCOri0oIC
Content-Disposition: form-data; name="file"; filename="image_02.jpg"
Content-Type: image/jpeg

------WebKitFormBoundaryHEiJYOCkCOri0oIC--

**Comment by dougwilson** [comment]
Hi @AbhijeetGiram I can take a look, though need something to investigate. Can you provide all the following?

1. Version of this module
2. Version of Node.js
3. Complete server code that replicates the issue I can copy and paste and run
4. Instructions for how to reproduce the issue using the provided server code

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
