### ISSUE TITLE
Error: Stream ended Unexpectedly

### ISSUE THREAD

**Issue by agarwal57** [pillarjs/multiparty#188]
Was trying to parse the request again using the multiparty, and it is resulting in the above error.
Code Snippet:

var formParser = new Promise((resolve, reject) => {
    var form = new multiparty.Form();
    form.parse(req, (err, fields, files) => {
      console.log(err);
      console.log('fields = ', JSON.stringify(fields));
      console.log('files = ', JSON.stringify(files));
      resolve();
      //res.writeHead(200, {'content-type': 'text/plain'}).end();
    });
  });
  formParser.then(() => {
    var newForm = new multiparty.Form();
    newForm.parse(req, (error, field, file) => {
      console.log('headers is ', req.headers);
      console.log('fields = ', JSON.stringify(field));
      console.log('files = ', JSON.stringify(file));
      console.log(error);
      res.send('Hello World');
    });
  });

**Comment by dougwilson** [comment]
In Node.js, the HTTP stream is only consumable once, unfortunately.
