### ISSUE TITLE
 Upload large files   multiparty  Request aborted 

### ISSUE THREAD

**Issue by 746655242** [pillarjs/multiparty#190]
"multiparty": "^4.1.3" 
 Upload large files   multiparty  Request aborted 

Error: Request aborted
    at IncomingMessage.onReqAborted (/home/hemaj/sports/node_modules/multiparty/index.js:183:17)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at abortIncoming (_http_server.js:405:9)
    at socketOnClose (_http_server.js:399:3)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:546:12)

After updating the most recent version, upload tens of KB pictures on the error: Request aborted.
Who help me look?
Thank you!

@Douglas Wilson

**Comment by dougwilson** [comment]
Thanks for the report! Can you help provide the following?

1. Version of Node.js
2. Example server code demonstrating the issue I can run
3. Instructions on how to reproduce. 

Thanks!

**Comment by 746655242** [comment]
node version v8.0.0
"express": "^4.14.0"

Form code:
` <form  action="/api/uppic?dir=image" method="post" target="_blank" enctype="multipart/form-data" >
        <input type="file" name="imgFile">
        <input type="submit">
    </form>`

node code：
`app.route('/api/uppic').post(function(req,res){
		
		
		var multiparty = require('multiparty');	
		var form = new multiparty.Form();
		form.encoding = 'utf-8';
		var ymd=new Date().toLocaleDateString();
		form.uploadDir = "Uploads/gaoxiao/"+ymd+'/';
		form.keepExtensions = true;   
		form.maxFieldsSize = 5*1024*1024; 
		form.maxFilesSize= 15*1024*1024;
		
		//Check the file exists
		var fs=require('fs');
		fs.exists(form.uploadDir,function(exists){  
			if(exists){
			}else{
				fs.mkdir(form.uploadDir);
			}
			fn();
		}); 

		function fn(){
			form.parse(req, function(err,fields,files) {
				if(err){
					console.log(err)
					var u={"error" :1,"message":'Please upload pictures within 15M'};
					res.end(JSON.stringify(u));
					return false;
				}	
				var suffix=/(.jpg|.gif|.jpeg|.png|.js|.css|.ico|.map|.otf|.eot|.svg|.ttf|.woff|.woff2|.mp3|.mp4|.webm)$/;		

				
				var oldpath=files.imgFile[0]['path'];
				if(!suffix.test(oldpath)){
					var u={"error" :1,"message":'Please upload the correct format'};
					res.end(JSON.stringify(u));
					return false;
			 	}
				var a=oldpath.split('.');
				var gs='.'+a[1];
							
				//Change the name of the image
				var url='Uploads/gaoxiao/'+ymd+'/'+Date.now()+gs;
				fs.renameSync(oldpath,url);
				var u={ "error" : 0, "url" : '/'+url}
				res.end(JSON.stringify(u));	
			});
		} 
	});`

Images can be uploaded within 10kb, more than 10kb image upload to terminate.
Thank you!


@douglaswilson

**Comment by 746655242** [comment]
Problem has been solved, my own problem, run with pm2, open the watch monitor, generate a file, the service automatically restart, resulting in the picture upload failed, thank you!

**Comment by dougwilson** [comment]
It's no worry, glad you got it resolved!
