### ISSUE TITLE
File upload not working with https

### ISSUE THREAD

**Issue by ghatul** [pillarjs/multiparty#191]
Hi, I am working with profile picture upload. I used multiparty to store the file in the directory it work's with HTTP but when I tested with https then profile upload failed. The file is not going to upload in the directory. Whats going wrong don't know could you please help me. Is multiparty support with https?

**Comment by ghatul** [comment]
Ok, I created self-signed certificate(SSL) and tested on https://localhost:800. Please refer below code...

`import * as multiparty from "multiparty";

export function uploadFile(req: express.Request, res: express.Response, next: any): void {

  __dirname = path.resolve() + config.get('config.path');
  let form = new multiparty.Form({uploadDir: __dirname});
  form.parse(req, (err: Error, fields: any, files: any) => {
    if (err) {
      next(err);
    } else {
      let path = JSON.stringify(files.file[0].path);
      let file_path = files.file[0].path;
      )};
}
`

File path and a new file(image) name are returned but the file is not uploaded to that directory path.

**Comment by dougwilson** [comment]
Thanks! That code looks like it is missing a lot. Can you provide the instructions for what steps I need to do to (1) run the code (I just get an error about import not existing when I copy paste and ran) and (2) how exactly to make the same upload request that you're making (could be an issue there, maybe).

Thanks!

**Comment by ghatul** [comment]
@dougwilson ,

and for server:
var spdy = require('spdy');

spdy.createServer(options, app)
      .listen(port, (error: any) => {
        if (error) {
          console.error(error)
          process.exit(1);
        } else {
          console.log('http2 Listening on port: ' + port + '.');
        }
      })

**Comment by dougwilson** [comment]
Hi @ghatul can you provide request (2) as well, please?

**Comment by dougwilson** [comment]
Your serve code above doesn't even use `multiparty`.

**Comment by ghatul** [comment]
@dougwilson 

Resolved, 

I replaced spdy with https. Maybe there is a problem with spdy module.
Thanku
