### ISSUE TITLE
stream ended unexpectedly

### ISSUE THREAD

**Issue by Ishneetkaur** [pillarjs/multiparty#192]
I am using this https://github.com/pillarjs/multiparty/blob/master/examples/s3.js to upload to s3 a file with following part details:
```
PassThrough {
    _readableState: 
     ReadableState {
       objectMode: false,
       highWaterMark: 16384,
       buffer: BufferList { head: null, tail: null, length: 0 },
       length: 0,
       pipes: null,
       pipesCount: 0,
       flowing: null,
       ended: false,
       endEmitted: false,
       reading: false,
       sync: false,
       needReadable: true,
       emittedReadable: false,
       readableListening: false,
       resumeScheduled: false,
       defaultEncoding: 'utf8',
       ranOut: false,
       awaitDrain: 0,
       readingMore: false,
       decoder: null,
       encoding: null },
    readable: true,
    domain: null,
    _events: 
     { end: [ [Object], [Function] ],
       prefinish: { [Function: bound onceWrapper] listener: [Function] },
       drain: [Function] },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: 
     WritableState {
       objectMode: false,
       highWaterMark: 16384,
       needDrain: false,
       ending: false,
       ended: false,
       finished: false,
       decodeStrings: true,
       defaultEncoding: 'utf8',
       length: 0,
       writing: false,
       corked: 0,
       sync: true,
       bufferProcessing: false,
       onwrite: [Function: bound onwrite],
       writecb: null,
       writelen: 0,
       bufferedRequest: null,
       lastBufferedRequest: null,
       pendingcb: 0,
       prefinished: false,
       errorEmitted: false,
       bufferedRequestCount: 0,
       corkedRequestsFree: 
        CorkedRequest {
          next: null,
          entry: null,
          finish: [Function: bound onCorkedFinish] } },
    writable: true,
    allowHalfOpen: true,
    _transformState: 
     TransformState {
       afterTransform: [Function],
       needTransform: false,
       transforming: false,
       writecb: null,
       writechunk: null,
       writeencoding: null },
    headers: 
     { 'content-disposition': 'form-data; filename="Tools_build_error.txt";',
       'content-type': 'text/plain' },
    name: null,
    filename: undefined,
    byteOffset: 143,
    byteCount: 13042 }
```

**Comment by Ishneetkaur** [comment]
It gives error for other file types too. I added ContentType too to the s3client. But still get the error?

`PassThrough {
    _readableState: 
     ReadableState {
       objectMode: false,
       highWaterMark: 16384,
       buffer: BufferList { head: null, tail: null, length: 0 },
       length: 0,
       pipes: null,
       pipesCount: 0,
       flowing: null,
       ended: false,
       endEmitted: false,
       reading: false,
       sync: false,
       needReadable: true,
       emittedReadable: false,
       readableListening: false,
       resumeScheduled: false,
       defaultEncoding: 'utf8',
       ranOut: false,
       awaitDrain: 0,
       readingMore: false,
       decoder: null,
       encoding: null },
    readable: true,
    domain: null,
    _events: 
     { end: [ [Object], [Function] ],
       prefinish: { [Function: bound onceWrapper] listener: [Function] },
       drain: [Function] },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: 
     WritableState {
       objectMode: false,
       highWaterMark: 16384,
       needDrain: false,
       ending: false,
       ended: false,
       finished: false,
       decodeStrings: true,
       defaultEncoding: 'utf8',
       length: 0,
       writing: false,
       corked: 0,
       sync: true,
       bufferProcessing: false,
       onwrite: [Function: bound onwrite],
       writecb: null,
       writelen: 0,
       bufferedRequest: null,
       lastBufferedRequest: null,
       pendingcb: 0,
       prefinished: false,
       errorEmitted: false,
       bufferedRequestCount: 0,
       corkedRequestsFree: 
        CorkedRequest {
          next: null,
          entry: null,
          finish: [Function: bound onCorkedFinish] } },
    writable: true,
    allowHalfOpen: true,
    _transformState: 
     TransformState {
       afterTransform: [Function],
       needTransform: false,
       transforming: false,
       writecb: null,
       writechunk: null,
       writeencoding: null },
    headers: 
     { 'content-disposition': 'form-data; filename="test2.fbx";',
       'content-type': 'binary/octet-stream' },
    name: null,
    filename: undefined,
    byteOffset: 140,
    byteCount: 192863646 }`

**Comment by Ishneetkaur** [comment]
I used connect-multiparty and it got fixed. Thanks.

**Comment by Ishneetkaur** [comment]
The object gets copied to s3 but gives this error. " stream ended unexpectedly" [no longer using connect-multiparty]

**Comment by dougwilson** [comment]
Hi @Ishneetkaur very strange. Unfortunately I'm not familiar with S3 and the example was kindly contributed to show users. If you know what changes we need to make to the example, we'll gladly make them 👍

**Comment by Ishneetkaur** [comment]
`Error: stream ended unexpectedly
    
    - index.js:754 Form.<anonymous>
      [webapp]/[multiparty]/index.js:754:24
    
    - events.js:91 emitNone
      events.js:91:20
    
    - events.js:188 Form.emit
      events.js:188:7
    
    - _stream_writable.js:510 finishMaybe
      _stream_writable.js:510:14
    
    - _stream_writable.js:520 endWritable
      _stream_writable.js:520:3
    
    - _stream_writable.js:485 Form.Writable.end
      _stream_writable.js:485:5
    
    - _stream_readable.js:513 IncomingMessage.onend
      _stream_readable.js:513:10
    
    - events.js:293 Object.onceWrapper
      events.js:293:19
    
    - events.js:91 emitNone
      events.js:91:20
    
    - events.js:188 IncomingMessage.emit
      events.js:188:7
    
    - _stream_readable.js:975 endReadableNT
      _stream_readable.js:975:12
    
    - next_tick.js:80 _combinedTickCallback
      internal/process/next_tick.js:80:11
    
    - next_tick.js:128 process._tickDomainCallback
      internal/process/next_tick.js:128:9
    
`

**Comment by Ishneetkaur** [comment]
Error: stream ended unexpectedly
    
    - index.js:754 Form.<anonymous>
      [webapp]/[multiparty]/index.js:754:24
    
    - events.js:91 emitNone
      events.js:91:20
    
    - events.js:188 Form.emit
      events.js:188:7
    
    - _stream_writable.js:510 finishMaybe
      _stream_writable.js:510:14
    
    - _stream_writable.js:520 endWritable
      _stream_writable.js:520:3
    
    - _stream_writable.js:485 Form.Writable.end
      _stream_writable.js:485:5
    
    - _stream_readable.js:513 IncomingMessage.onend
      _stream_readable.js:513:10
    
    - events.js:293 Object.onceWrapper
      events.js:293:19
    
    - events.js:91 emitNone
      events.js:91:20
    
    - events.js:188 IncomingMessage.emit
      events.js:188:7
    
    - _stream_readable.js:975 endReadableNT
      _stream_readable.js:975:12
    
    - next_tick.js:80 _combinedTickCallback
      internal/process/next_tick.js:80:11
    
    - next_tick.js:128 process._tickDomainCallback
      internal/process/next_tick.js:128:9

**Comment by Ishneetkaur** [comment]
How ould you set the boundary..? It that causing this issue?

**Comment by dougwilson** [comment]
The boundary is part of the `Content-Type` header, as the `boundary` parameter. I'm not sure what is causing the issue in your situation. Maybe if you can provide compete instructions for how I can reproduce the issue, I can also take a look with a debugger 👍
