### ISSUE TITLE
Feature suggestion: expose content id's on parts that have Content-Id headers.

### ISSUE THREAD

**Issue by npryce** [pillarjs/multiparty#195]
The CID URL scheme and Content-Id headers (https://tools.ietf.org/html/rfc2392) are used to link parts of multipart content.  It would be nice if Multiparty recognised Content-Id headers and exposed a part's content id as a property of the part if it had a Content-Id header.

**Comment by dougwilson** [comment]
Nice, I didn't even know any web browsers included that header. Which web browsers are doing that, just to be curious? As far as exposing, all the headers for each part are already exposed under the `headers` property of the part object. Is this what you're looking for? If not, can you clarify the request?

**Comment by npryce** [comment]
Web browsers do not (as far as I know), but multipart content types are used in many other contexts and transmitted by other protocols.

**Comment by dougwilson** [comment]
Ah. Which protocols is that? This module is tightly coupled to HTTP currently, so I wonder if we should extend the parser to read in from other protocols?

**Comment by npryce** [comment]
Multipart content types were originally designed for email.  Our project receives multipart/mixed over HTTP, so being coupled to node's Request class isn't a problem.

**Comment by dougwilson** [comment]
Cool. So, circling back, what is the answer to my original question?

**Comment by dougwilson** [comment]
Closing due to no response. No idea what changes to make to the module.
