### ISSUE TITLE
maxFieldsSize string or number?

### ISSUE THREAD

**Issue by ORESoftware** [pillarjs/multiparty#196]
is `maxFieldsSize` a string or a number?

<img width="1081" alt="screenshot 2018-05-01 16 25 12" src="https://user-images.githubusercontent.com/11139560/39498341-7f340ad6-4d5c-11e8-96ae-6c8845df75c5.png">

```js
  let form = new multiparty.Form({
    encoding: 'utf8',
    maxFieldsSize: '18mb',
    maxFields: 1, //one file?
    maxFilesSize: '18mb'
  });
```
  
if the type is wrong, please throw an error in the next major version!

**Comment by ORESoftware** [comment]
there really should be example of sane defaults in the readme, I can't tell if `maxFieldsSize` is in bytes or megabytes, etc.

**Comment by dougwilson** [comment]
Pull requests to improve the above are welcome!

**Comment by dougwilson** [comment]
Readme says "in bytes" for that field, so it is bytes you want to specify :+1:
