### ISSUE TITLE
Throw error from `part` handler

### ISSUE THREAD

**Issue by pronebird** [pillarjs/multiparty#200]
Hi,

How do I stop the "train" if my code is unable to create a write stream to pipe the part from `part` event? Does multiparty handle exceptions thrown from `part` event handler?

**Comment by dougwilson** [comment]
No, it doesn't handle exceptions thrown in event handlers, similar to Node.js itself which doesn't handle any exceptions in event handlers. You'll need to handle it such that you implement the behavior you are expecting when that condition occurs.

**Comment by pronebird** [comment]
Is there any way to stop parsing immediately and return error if I find that there are some issues saving the readable stream?

**Comment by dougwilson** [comment]
Multiparty itself is just a Writable steam in Node.js so you should do whatever you would do with any other Writable stream.

If you called .pipe to pipe to mulitparty than you'll want to call .unpipe to stop sending the data to multiparty if you want it to stop parsing. It's just parsing as the readable stream pushes to multiparty.

**Comment by dougwilson** [comment]
Ex `req.unpipe(form);` assuming your request is req and your muktiparty instance is form.
