### ISSUE TITLE
Ability to get file as Buffer and not save to disk.

### ISSUE THREAD

**Issue by justablob** [pillarjs/multiparty#203]
I'm building a semi-stateless application with no "real" local disk and I do not want multiparty to try to write to it. Instead, I'd like to see a feature which waits until all data is recieved and then passes a "rawData" prop alongside all files. I would implement it myself however I don't understand a single line of the code... Looks obfuscated to me almost.

**Comment by dougwilson** [comment]
The raw data is available without writing to disk using the `part` event: https://github.com/pillarjs/multiparty#part-part

The s2 and azure example make use of this if you're looking for more examples outside of the readme 👍 https://github.com/pillarjs/multiparty/tree/master/examples

**Comment by justablob** [comment]
Correct me if I'm wrong, but the testing which I did on my own machine, using the part event, it still did write to the Temp folder. It's a Windows 10 machine.

**Comment by dougwilson** [comment]
Even if you add the part event, if you have the options set to write to disk, it will still do that. Can you share the code?

**Comment by justablob** [comment]
I removed my event handler code for security reasons.

```js
    const form = new multiparty.Form()
    form.parse(req)
    form.on("part", part => {
      // uploading logic
    })
```

**Comment by dougwilson** [comment]
Yea, that shouldn't write anything to disk.

**Comment by justablob** [comment]
I see a file being created in Temp, and it happens even after commenting out my uploader code. It might be some other part of my code, but I believe it's related to multiparty.

**Comment by dougwilson** [comment]
I can certainly take a look. Is it possible you can provide all the following so I can reproduce and investigate?

1. Version of node.js
2. Version of this module
3. A complete code file I can copy and paste and run as is without modifications
4. Instructions for how to reproduce the issue with the given code.

Thanks!

**Comment by justablob** [comment]
This is a test project after all (in production we use good old busboy) and I guess if we ever do decide to use multiparty in production, we can attach a little Ceph store to the container so I don't waste your time.

**Comment by justablob** [comment]
Alright. 
Node.js version: v10.7.0
Multiparty version: v4.1.4
File: 

```js
const fs = require("fs-nextra")
const url = require("url")
const multiparty = require("multiparty")
const { Server: Server } = require("http")

onst server = new Server(async (req, res) => {
  const { path } = url.parse(req.url)
  if (path === "/upload" && req.method === "POST") {
    const form = new multiparty.Form()
    form.parse(req)
    form.on("part", part => {
      // uploading logic
      console.log(part.filename) // just as an example
    })
  }
})

server.listen(49566)
```

Now just do a POST request to `/upload` with a multipart form with a file in it attached to it and look at your Temp folder. In my case, it wrote a file with a random name and the extension of the source file containing the contents of the actual file aswell.

**Comment by dougwilson** [comment]
Thanks! So I just deleted everything from my temp (as returned by `os.tmpDir()` in Node.js, which is what this uses) and ran your server (installed latest `fs-nextra`, I hope that is OK version) then used a form with just one file field and selected a file to POST and the temp dir remained empty.

**Comment by justablob** [comment]
Alright, I guess I'll have to search if the problem lies somewhere else. I really want to try to use something new, while busboy is great, I think that multiparty is a lot easier to use and I also think it should be more reliable. With that said, I could not reproduce this either with the code I've sent you so multiparty is not the issue. Sorry for wasting your time.

**Comment by dougwilson** [comment]
Hey, it's no problem. I'm happy to help and if there is an issue definitely would like to fix it :+1:

**Comment by esseswann** [comment]
Interestingly it still does on Windows
![image](https://user-images.githubusercontent.com/6066417/74092934-2effd480-4adc-11ea-8ab3-ac9851cd3dd3.png)
