### ISSUE TITLE
Parse Callback is called before writing to desc

### ISSUE THREAD

**Issue by Attrash-Islam** [pillarjs/multiparty#204]
Hi maintainers,

First of all, thanks a lot for your nice plugin that I used years ago and returned to use it again because I'm so satisfied from your simple API.

I'm facing something strange when uploading 35 images from a High Quality Canon Camera (~6MB per image), and then I got the temp file names in my outDir with an inner value of the originalFileName. Then I'm renaming this temp name with the saved original file name that I get in the parse callback.

I see that it successes with lower quantities of images but when I upload 35 image I got the exception of file not exist when trying to rename it with the path supplied by the callback..

I assume that the callback is called before finishing writing to desc. Is there a chance that I'm not configuring the things right or it is a bug?

Waiting to hear from you,
Thanks again

**Comment by Attrash-Islam** [comment]
```js
app.post("/api/images/upload", (req: core.Request, res: core.Response) => {
		const form = new multiparty.Form({
			autoFiles: true,
			uploadDir: `${baseDir}${IMAGES_FILES_CLIENT_DIR}`,
		});

		form.parse(req, async (err, fields, files: File[]) => {
			if (err) {
				sendErrorResponse(res, err);
				return;
			}

			const sentFileKeys = Object.keys(files);
			for (let key of sentFileKeys) {
				const file = files[key][0];

				renameFile(file.path, `${IMAGES_FILES_DIR}/${file.originalFilename}`);
				await createPreviewImageFile(IMAGES_FILES_DIR, file.originalFilename);
			}

			res.status(200).send();
    });
  });
```

**Comment by Attrash-Islam** [comment]
When I replaced renameFileSync with renameFile but still using a Promisified version with await it's not producing!

**Comment by dougwilson** [comment]
I'm sorry you're having trouble using the module. I took the code and information above and tries to reproduce the issue but I was not successful in doing so :( I would need to be able to reproduce the issue if the expectation is that I form the bug fix, of course. To that end, can you please provide all the following?

1. Version of Node.js, this module, and any other module used in your code provided.
2. Complete code that is standalone in which I can copy and paste and run without modification. It does not have to be your real code, just needs to be runnable and reproduce the issue.
3. Complete steps needed to reproduce the issue. If only certain files are triggering it, I need a way to match those as well.

Thanks!
