### ISSUE TITLE
Unable to parse files with name having more than 36 character.

### ISSUE THREAD

**Issue by angsdey2** [pillarjs/multiparty#205]

**Comment by dougwilson** [comment]
I'm sorry you're having trouble using the module. I took the information above and tried to reproduce the issue but I was not successful in doing so :( I would need to be able to reproduce the issue if the expectation is that I form the bug fix, of course. To that end, can you please provide all the following?

1. Version of Node.js, this module, and any other module used in your code provided.
2. Complete code that is standalone in which I can copy and paste and run without modification. It does not have to be your real code, just needs to be runnable and reproduce the issue.
3. Complete steps needed to reproduce the issue. If only certain files are triggering it, I need a way to match those as well.

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
