### ISSUE TITLE
Clarity: part.filename is empty with no uploads

### ISSUE THREAD

**Issue by thetutlage** [pillarjs/multiparty#207]
When reading the README file, there is an example, which helps in distinguishing between a `file` and `field` part.

```
if (part.filename) {
  // file
} else {
  // field
}
```

However, `part.filename` will be an empty string, if form is submitted without selecting the file.

## Example

Here's an example of same

```js
var multiparty = require('multiparty');
var http = require('http');
var util = require('util');

http.createServer(function(req, res) {
  if (req.url === '/upload' && req.method === 'POST') {
    // parse a file upload
    var form = new multiparty.Form({
      autoFields: false,
      autoFiles: false      
    });

    form.on('part', (part) => {
      if (!part.filename) {
        console.log(`${part.name} is not a file`)
      } else {
        console.log(`${part.name} is a file`)
      }
    })

    form.parse(req)

    return;
  }

  // show a file upload form
  res.writeHead(200, {'content-type': 'text/html'});
  res.end(
    '<form action="/upload" enctype="multipart/form-data" method="post">'+
    '<input type="file" name="upload"><br>'+
    '<input type="submit" value="Upload">'+
    '</form>'
  );
}).listen(8080);
```

## Question
Is it that README is not updated and we should check for the `null` vs truthiness of the property?

```js
if (part.filename !== null) {
  // file
} else {
  // field
}
```

Or is their more to the story?

**Comment by dougwilson** [comment]
I believe you are correct. There is no reason the filename cannot be an empty string.

**Comment by thetutlage** [comment]
So do you think the solution is to explicitly check for `null`?

**Comment by dougwilson** [comment]
I would need to test at a computer to see what the exact right answer is. If you can test and that works, then that is the answer.

**Comment by dougwilson** [comment]
I was just going to add a field to your example HTML to test it out and make sure the change doesn't accidentally cause the field to go down the file part, for example.
