### ISSUE TITLE
Req.files empty on Heroku

### ISSUE THREAD

**Issue by erictraub** [pillarjs/multiparty#209]
I am using multiparty to access the files in my express routes.  Multipary is working great locally but when I push the application to Heroku, req.files is always an empty object.  What is the reason for this?

**Comment by dougwilson** [comment]
Hi @erictraub sorry you're having trouble. I have never used Heroku, and have no idea what to tell you. Is that an environment where you can attach a debugger instance to your application and step though the code when a request comes in?

**Comment by dougwilson** [comment]
I'm going to close this since I never heard back.
