### ISSUE TITLE
unhandled exception on unclear conditions

### ISSUE THREAD

**Issue by puzrin** [pillarjs/multiparty#211]
I can not provide reproduceable condition, but strange unhandled exception goes from multiparty internals:

multiparty 4.1.3, node.js 8.9.4

```
[2018-12-11T02:46:39.279] [FATAL] 4598 system - UNCAUGHT EXCEPTION !!! TypeError: Cannot read property 'write' of null
    at Form.onParsePartData (/root/fontello/node_modules/multiparty/index.js:467:43)
    at Form._write (/root/fontello/node_modules/multiparty/index.js:414:10)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Form.Writable.write (_stream_writable.js:290:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
[2018-12-12T08:57:29.459] [FATAL] 3754 system - ***
ip:        86.60.122.98
url:       /io/rpc
request:   POST
responder: rpc
apiPath:   fontello.font.generate
params:    {
  "config": ""
}
```

https://github.com/pillarjs/multiparty/blob/4.1.3/index.js#L467 - this line.

---

Additional info:

- (?) probably, multiparty request with empty body + some rare race condition.
- we use multiparty.parse() with callback (error handlers set internally), [code](https://github.com/nodeca/nodeca.core/blob/f361c8ad772057c7cdef05860ef1a75a582969f8/lib/autoload/hooks/responder/rpc/rpc_prepare.js#L48)

I understand, here not enough info to say exactly what happens, but may be you have some idea? I could not find what i do wrong.

May be, some issue in bode streams, fixed in newer versions?

**Comment by dougwilson** [comment]
Hi @puzrin thanks for the report. Without a clear reproduction case, I'll have to poke around to see if I can figure out what would cause it. I would definitely recommend using the current version of this module to see if that resolves the issue, though, as it may already be fixed. But if not, the fix would be made against the current version, so you'd have to upgrade anyway.

**Comment by puzrin** [comment]
I already upgraded everything.

https://github.com/fontello/fontello/issues/677#issuecomment-446351609 the only available info except log - author's comment about mailformed request body.

**Comment by dougwilson** [comment]
Oh, did the error occur again after the upgrades?

**Comment by puzrin** [comment]
We could not find crashing sequence both before and after upgrade. Server worked years with node 8 without problems.

I also not 100% sure problem is multiparty, and ok if you close issue. Posted here to ask, may be you have ideas about possible races on streams close.

**Comment by dougwilson** [comment]
Gotcha. I dud spend a couple hours trying to figure it out today but was not successful. We don't need to close it, at least right now it's not obviously not an issue with this module, though just trying to figure out what the condition is. I will take another look later this week as well.

**Comment by dougwilson** [comment]
Hi @puzrin I'm really sorry. I spent a couple days again digging in to this and I cannot find any possible code path this particular error can occur, barring outside manipulation of the internal state of this module. I wish I had better news, but it's just sadly unclear how to fix it at this time.
