### ISSUE TITLE
part "index" or count?

### ISSUE THREAD

**Issue by lamontadams** [pillarjs/multiparty#212]
Hey guys,

I'm working on wiring up multiparty to AWS S3's multipart upload methods. I'm stuck at handling `"part"` events because the S3 API's [uploadPart](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#uploadPart-property) method expects a PartNumber parameter. I don't see a way to get this from any of the properties exposed by `part` and I'm not sure how to infer a part number short of the really naive and error-prone idea of just incrementing a counter. Even trying to do something like counting bytes seems impossible because I don't see any sort of chunk-size parameter anywhere.

Am I missing something or is this not possible?

Thanks.

**Comment by dougwilson** [comment]
Does that API _require_ the PartNumber to work? if so, there is no concept of something called a part number or anything in the multipart specification. What does a PartNumber mean in the S3 API?

**Comment by lamontadams** [comment]
It's documented as

**Comment by dougwilson** [comment]
So each part event (a part in the sense of a multipart request) is a complete file. So you wouldn't want to assemble them together into a single blob, right?

**Comment by lamontadams** [comment]
Yeah, I'm being lazy here and trying very hard to avoid assembling them (explicitly or implicitly) inside my service... this use case is for files on the large side. Ideally I want to just hand off the pieces to S3 as I get them.

**Comment by dougwilson** [comment]
I see. So you're saying that you're actually sending _one file_ across several parts of a multipart request? As in each part in the multipart request is not a complete file? In that case, you likely want to add a header of the part number within each part, and that would be available as `part.headers['you-header-name']` to use in the S3 request.

**Comment by lamontadams** [comment]
I'm not sure we're on the same page ;) 

I'm uploading large files from a browser using FilePond which manages the multipart upload of a single file. FilePond talks to my HTTP endpoint which uses multiparty to handle parsing the payload. I'm handling multiparty's form events to hand pieces off to S3's multipart upload method as the events are being fired - which is where I came in here.

The goal here is to avoid reading the whole file into memory (which is the naive implementation I'm trying to replace) or spooling them out to disk (we're destined to run in a container).

**Comment by dougwilson** [comment]
Yea, sorry, I'm trying my best from what my own background knowledge is and what is being said here. I'm sure what you're saying makes sense to you, but (1) I've never used S3 and (2) never heard of or used FilePond so there is a lot of unknowns on my side.

I am familiar with multipart. Perhaps you can walk me through what the raw multipart bytes look like over the wire, like how FilePond is constructing them, and then show me with that example what the PartNumber of each part should be for S3 and I can better understand what the multipart looks like and what you're trying to get out of it?

Or maybe you have a different idea to better get us in sync so I can help :)

**Comment by lamontadams** [comment]
Filepond is a black box to me, I just know it handles the multi-part post. I threw together a logging-only implementation on the server and I'm seeing weird things.

Should I expect the "part" event to only raise once for any given filesize? 

I've tested locally with some files sized up to 100MB and while "progress" is raised repeatedly (with sane, sequential `received` values) I only seem to get "part" raised once with the total size of the file reported as `part.byteCount`. 

I was expecting `part` to raise repeatedly. Is this because I'm calling `part.resume()`?

**Comment by dougwilson** [comment]
The part event is raised for every part that is in the multipart request. It sounds like FilePond is just sending the entire file as a single part... https://github.com/pillarjs/multiparty/issues/212#issuecomment-511513751

**Comment by lamontadams** [comment]
Hmm. I'm obviously not understanding something. I'm getting progress events on both sides that sure look like I'm getting a file broken into multiple "chunks". I assumed these chunks were "parts" but that's not necessarily the case?

**Comment by dougwilson** [comment]
Without providing me something I can look at and see the same thing, it's hard to say for sure.

**Comment by dougwilson** [comment]
But if you're only getting one part event and the byteCount is the length of the entire file, it would seem to me like it's just a single part that FilePond is sending... ?

**Comment by lamontadams** [comment]
In the absence of any evidence to the contrary I have to agree with you. I'm digging at FilePond's documentation - all I can find is that it mentions it uploads files as `multipart/form-data`. But I only ever see one part in the raw post data. 

So I guess the answer in my case is: don't use S3's multipart upload. 

Thanks for talking through this with me anyway. You're a good duck. :+1:

**Comment by dougwilson** [comment]
It's no problem :)
