### ISSUE TITLE
In request with both text and file, byteCount of the file part is incorrect 

### ISSUE THREAD

**Issue by sosloow** [pillarjs/multiparty#213]
We use multiparty to stream formData requests to a service similar to s3. Recently we added some text fields in that request, and it stopped working.

We discovered that, if you send formData with fields ordered like this, method works:

```
field1: text
field2: text
file: binary
```

But if you rearrange fields in the request like this, `part.byteCount` returns an incorrect value - presumably file size+length of the text field part:

```
file: binary
field1: text
field2: text
```

Here's our code:

```javascript
const form = new multiparty.Form({});

form.on('field', (name, value) => {
    if (name === 'foo' || name === 'bar') {
        // ...
    }
}

form.on('part', (part) => {
    this.fileStore.put({
        id: SOME_ID,
        type: CONTENT_TYPE,
        size: part.byteCount,
        body: part,
    });
});

form.parse(req);
```

Could there be something wrong with our code? Or maybe it's an intended behavior?

**Comment by dougwilson** [comment]
That field is only the size of the part if it is the last part, from the readme:

> byteCount - assuming that this is the last part in the request, this is the size of this part in bytes.

**Comment by sosloow** [comment]
Thanks,

is there any way to get the file size, if the fields are sent in an arbitrary order?

**Comment by dougwilson** [comment]
Unless the part has a content-length header, then you have to read the entire stream and count the bytes.

**Comment by sosloow** [comment]
Thanks a lot, I'll think about it.
