### ISSUE TITLE
Getting `BadRequestError: stream ended unexpectedly`

### ISSUE THREAD

**Issue by Idomo** [pillarjs/multiparty#214]
Hi, I've noticed that many issues have already opened about this error, but none of them had  a working solution.

I'm using this package with Node.JS & Firebase Functions.

**My goal - upload the file to the `temp` directory and let me do the rest of the work**

I've tried for days to search for some package that can do that simple thing.
From some reason `Formidable` didn't even fired the callback that sent to the parser and the rest of the packages just based on express (which I'm not using here as much as I know).

I'd really appreciate any kind of help to achieve my goal.

HTML form:
``` HTML
<form action="url/to/uploadFile" method="POST" enctype="multipart/form-data">
  <input type="text" name="path" value="path/to/image.jpg">
  <input type="file" name="fileToUpload">
  <button type="submit">Submit</button>
</form>
```

JS code:
``` JS
const functions = require('firebase-functions');
const multiparty = require('multiparty');

exports.uploadFile = functions.https.onRequest((req, res) => {
  if(req.method !== 'POST'){
    return res.status(405).end(); // Return a "method not allowed" error
  }

  const form = new multiparty.Form();

  return new Promise((resolve, reject) => {
    form.parse(req, function(err, fields, files){
      console.log(`Error: ${err}`);
      console.log(`Fields: ${fields}`);
      console.log(`Files: ${files}`);
      res.writeHead(200, {'content-type': 'text/plain'});
      res.write('received upload:\n\n');
      res.end(/*{fields: fields, files: files}*/);
    });
  });
});
```

Console:
``` 
>  Error: BadRequestError: stream ended unexpectedly
>  Fields: undefined
>  Files: undefined
```

**Comment by dougwilson** [comment]
Hi, and thanks for the report! I've never used Firebase functions, so no idea if this module is actually compatible with them, which may be why it's not working.

The error itself is that the `req` object signaled that the data stream ended but the parser in this module did not expect it to end. The multipart format has a way to indicate the end of the data, so if this module sees that `req` is ended before encountering this marker, then you get the error above.

Can you replace `multiparty` usage with the following and then paste the produced output here?

```js
req.on('data',(c) => console.log(c.toString('hex')))
req.on('end', () => console.log('ended')
```

**Comment by Idomo** [comment]
@dougwilson Tried this, getting timeout (more than 60s).
You meant to do this, right?
```JS
exports.uploadcdFile = functions.https.onRequest((req, res) => {
  if(req.method !== 'POST'){
    return res.status(405).end(); // Return a "method not allowed" error
  }
  req.on('data',(c) => console.log(c.toString('hex')));
  req.on('end', () => console.log('ended'));
});
```

**Comment by dougwilson** [comment]
Yea, you will see a timeout on the client, but it doesn't matter. It should still produce output from those `console.log`s

**Comment by Idomo** [comment]
This is all I get in the console:
```
  functions: Beginning execution of "uploadcdFile"
⚠  functions: Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
```

**Comment by dougwilson** [comment]
So are you actually uploaded a file when that happens? What exactly is the `req` object? Does it emit `data` events and the `end` event or something else?

**Comment by dougwilson** [comment]
I guess another question would be, can you actually see output from a `console.log` in general from within a Firebase function?

**Comment by Idomo** [comment]
The module should upload the file as far as I understand, I need just the path to the file in the `temp` directory, but since I'm getting this error I assume that it didn't uploaded the file.

Yes, of course I can, you can see at the opening comment that I've posted the `console log`s.

**Comment by dougwilson** [comment]
Gotcha. So I guess then it sounds like the issue here is that `req` does not emit any data in the `data` event, otherwise you'd see those `console.log` printouts. What exactly is the `req` object? Does it emit `data` events and the `end` event or something else? How do you read the raw body stream in a Firebase function?

**Comment by Idomo** [comment]
`req.rawBody`, it's a regular `Request` object that coming from node.js.

**Comment by dougwilson** [comment]
Ah. So this module needs the data to be coming in as a stream, not in a variable. There is no such property `rawBody` that is part of Node.js request objects, so not sure where that would be coming from. https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_class_http_incomingmessage

The Node.js request object is of the type `http.IncomingMessage` (https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_class_http_incomingmessage) and the data comes in from `data` events that are emitted and then `end` event end it is done. This is what this module expects.

**Comment by Idomo** [comment]
Just looked dipper and found that it does using Express 4.17, it may change things? I did saw that in other issues about this the `bodyParser` made problems, but I'm not sure how to disable it (if necessary).

**Comment by dougwilson** [comment]
There is no such thing as a `rawBody` property in Express, either. This module follows the Node.js documentation for how to get the data from a Node.js request object: https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/#request-body

**Comment by Idomo** [comment]
This is the definition of `rawBody`:
```JS
export interface Request extends express.Request {
    rawBody: Buffer;
}
```

**Comment by dougwilson** [comment]
This module is agnostic of Express or any framework. It's just meant to work on the Node.js request object directly. Can you pass in the Node.js request object? If not, you may need to find some kind of Firebase-specific multipart-parsing module.

**Comment by Idomo** [comment]
I don't think so, this is the request I'm getting.
I've made it work with `busboy`, it did fired the listener when it detected file and gave me the path to the file in the `temp` directory, but from some reason it didn't really uploaded the file (using `file.pipe(fs.createWriteStream(fileTempPath))), so I couldn't do anything with it.

**Comment by dougwilson** [comment]
AFAIK busboy works the same as this module, where it just operates off a Node.js request object as well. So You're likely having the same issue, just the way it manifests is different between this module and busboy.

**Comment by Idomo** [comment]
Well, anyway, thank you for your time.
Hope to find something that will work soon, I've already spent all last week on finding solution for this...

**Comment by KostyaTretyak** [comment]
In my case, I tried to parse `multipart/form-data` body after parsed ` application/json` body.

**Comment by dwelle** [comment]
For future readers, Firebase Functions pre-process `request.body` which is why no library on the market will work out of the box. Hence why you need to use the custom `req.rawBody` where normally you'd use `req.body`.

> Please read the [documentation for handling multipart form uploads](https://cloud.google.com/functions/docs/writing/http#handling_multipart_form_uploads).
> 
> > ... if you want your Cloud Function to process multipart/form-data, you can use the rawBody property of the request.
> 
> Because of the way Cloud Functions [pre-processes some requests](https://cloud.google.com/functions/docs/writing/http#parsing_http_requests), you can expect that some Express middleware will not work, and that's what you're running into. — [source](https://stackoverflow.com/a/48289899/927631)
