### ISSUE TITLE
Test failing on master branch in node 13.9.0

### ISSUE THREAD

**Issue by ryhinchey** [pillarjs/multiparty#217]
On node `13.9.0`, a test is failing on the `master` branch.  I'll look into why and work on a PR.  Tests all pass latest node LTS `12.16.1`.

test output:
```
> multiparty@4.2.1 test /Users/ryhinchey/Code/multiparty
> mocha --reporter spec --bail --check-leaks test/



  multiparty
    fixture tests
      content-type
        ✓ charset
        ✓ charset-last
        ✓ custom
        ✓ custom-equal-sign
      encoding
        ✓ menu_seperator.png
        ✓ beta-sticker-1.png
        ✓ blank.gif
        ✓ binaryfile.tar.gz
        ✓ plain.txt
      filename
        ✓ empty
        ✓ generic
        ✓ filename-name
        ✓ quotes
      preamble
        ✓ crlf
        ✓ preamble
      special-chars-in-filename
        ✓ osx-chrome-13
        ✓ osx-firefox-3.6
        ✓ osx-safari-5
        ✓ xp-chrome-12
        ✓ xp-ie-7
        ✓ xp-ie-8
        ✓ xp-safari-5
    standalone tests
      ✓ chunked
      ✓ connection aborted closed
      ✓ connection aborted
      ✓ content transfer encoding
      ✓ emit order
      ✓ epilogue last chunk
      ✓ error listen after parse
      1) error unpipe


  29 passing (144ms)
  1 failing

  1) multiparty
       standalone tests
         error unpipe:
     AssertionError [ERR_ASSERTION]: req has 1 pipe
      at Context.fn (test/test.js:358:14)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by ryhinchey** [comment]
looks like in the latest version of node, `pipesCount` was removed which is causing this test to fail:

`master`: https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L116
`12.16.1`: https://github.com/nodejs/node/blob/v12.16.1/lib/_stream_readable.js#L115

**Comment by dougwilson** [comment]
Good find! I don't see any mention of that in the changelog https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md

If this was me, my next step would be to raise an issue with Node.js to determine if this was intentional or a regression.

**Comment by ryhinchey** [comment]
there's this so I have to imagine it was intentional:

https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L1151-L1156

**Comment by dougwilson** [comment]
So what you linked to means that pipesCount is not removed, just changed to a getter, so it should still be there.

**Comment by ryhinchey** [comment]
`pipesCount` getter throws an error if used as follows. I'd expect it to return an empty array

```javascript
// node 13.9.0
var stream = require('stream');
var req = new stream.Readable();

req.pipesCount
// Uncaught TypeError: Cannot read property 'length' of undefined
    at Readable.get (_stream_readable.js:1138:25)

req._readableState.pipes
// []
```

**Comment by ryhinchey** [comment]
Looks like this is fixed on `master` in the node repo but not the `13.9.0` tag.  

`this.pipes` isn't initialized
https://github.com/nodejs/node/blob/v13.9.0/lib/_stream_readable.js#L1138

on `master`, it is:
https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L116

I can make a PR getting the tests to pass by doing something like this in the tests
` var pipesCount = req._readableState.pipesCount || req._readableState.pipes.length;`

**Comment by dougwilson** [comment]
So that sounds like a Node.js bug for sure, that accessing pipesCount is throwing a type error. It should be reported to Node.js for them to resolve, right?

**Comment by dougwilson** [comment]
So based on your new comment, no PR is necessary. It is a bug in Node.js that they fixed. Just wait for them to release the fix :+1:
