### ISSUE TITLE
Error while promisifying parse() method.

### ISSUE THREAD

**Issue by tasmia2016831022** [pillarjs/multiparty#220]
Instead of using a callback, if someone wants to promisify the form.parse() method, it cannot set 'autoFields' property while parsing  multipart/form-data. 

```javascript 
 let parse = util.promisify(form.parse)
parse(req).then(fields => {
    // code 
}).catch(error)
```
this gives an error "TypeError: cannot set property 'autoField' of undefined"

can this be resolved anyway ?

**Comment by dougwilson** [comment]
Can you provide the full stack trace and the version of this module you are using? I cannot reproduce the error.

**Comment by dougwilson** [comment]
Closing due to no response.
