### ISSUE TITLE
Can fields come after files?

### ISSUE THREAD

**Issue by msageryd** [pillarjs/multiparty#222]
I have moved from **Busboy** via **Formidable** to **Multiparty**. Multiparty is way easier to work with. I love how easy it is to stream files directly to S3. Thank you!

One issue I had with Busboy was that files sometimes came before the fields. I need the field data for several reasons:
- Abort the request if I don't find validation information in the fields
- Use field data to stream the files to the correct S3 buffer

Is it possible for fields to come after files with Multiparty?

**Comment by dougwilson** [comment]
Yes, they come in the exact order that the client sent them in to the server.

**Comment by msageryd** [comment]
Thanks.
Do you have any suggestion on how to await all fields before reading the part streams?

**Comment by dougwilson** [comment]
Because a part can be quite large, you would need to limit / buffer them somewhere while you wait for all the rest of the data you need like the fields. For example, you could write them to a temporary location on disk and then once you have the fields you need, write up the files from disk to S3.

Another solution could be to move the information you need to a different part of the request that _is_ guaranteed to come before files, like in request headers, the URL, the query string, etc.

**Comment by msageryd** [comment]
Unfortunately, I have no control of the part order. I'm parsing incoming emails from Sendgrid. I need to ensure that both the to- and from-fields are valid. These are sent as multipart fields from Sendgrid.

I don't want to mess with temp folders locally, as I'm running the servers in ephemeral containers at AWS Fargate.

I think I'll stream the files to S3 anyway and then remove them if I don't find the correct field data, or move them when I know which bucket they belong to. Maybe S3 has an automatic file-removal timeout so I don't need to handle the temp bucket at S3.

**Comment by msageryd** [comment]
Thank you for your speedy response!

**Comment by msageryd** [comment]
@dougwilson I'm wondering if the following would be a bad idea?

1. Wrap onField in a promise, which I'll resolve only after receiving the important fields which I need in order to start uploading files to S3. 

2. Also put a timeout in the field promise and reject if it takes to long to get the fields

3. In the onPart event I'll await the field promise before starting to handle the parts. If the promise rejects, I'll just `part.resume()`

**Comment by msageryd** [comment]
To clarify, this is the promise I had in mind:

```
 const inboxPromise = new Promise((resolve, reject) => {
    const inboxTimeout = setTimeout(
      () => reject(new Error('Timeout reached while waiting for inbox information.')),
      3000
    );

    form.on('field', async function(name, value) {
      if (wantedFields.includes(name)) {
        formMetadata[name] = value;

        if (formMetadata.to && formMetadata.from) {
          try {
            const inbox = await getInbox(formMetadata);
            clearTimeout(inboxTimeout);
            return resolve();
          } catch (e) {
            return reject(new Error('Invalid inbox'));
          }
        }
      }
    });
  });
```
