### ISSUE TITLE
How to await S3 upload from within onPart event?

### ISSUE THREAD

**Issue by msageryd** [pillarjs/multiparty#223]
I have the following scenario:

```
form.on('part', async function(part) {
  await s3Response = s3.upload({Bucket: BUCKET_NAME, Key: key, Body: part}).promise();
});

form.on('close', function() {
  return res.status(200).end();
});
```

I want to await the upload promise in order to handle any upload problems.

I'm probably doing something stupid, but the above solution does not work as I expected. The close event is fired before I get the response from S3.

If I remove the `await` the close event is fired in the correct order. How can I await the upload correctly without responding 200 prematurely?

**Comment by ryhinchey** [comment]
Try putting a try/catch around the await line and then put`return res.status(200).end();` after the await line.

In the catch, handle any upload errors from s3.  

The close event is fired after all parts have been parsed and emitted so it’s not surprising that it’s firing before you’re upload to s3 is complete.

Are you trying to upload a single file or multiple files?

**Comment by msageryd** [comment]
Thanks.
Aha, I thought "close" was some kind of collective close event for the part streams.

There can be multiple files. I'm parsing incoming emails.

I suppose I'll have to put the promises in an array and await "all" instead. But I wonder if this is safe timing-wise. I have some stuff I need to do in the part-event. I'm chaining the stream like this:
1. calculate md5 and file size in a Transform stream
2. check file-type by identifying "finger prints" in the start of the files
3. stream to s3

How can I be sure that all upload-promises have been added to the promise array before the close-event is fired? The close-event is where I need to await the promise array, right?

**Comment by dougwilson** [comment]
The standard method in the event emitter world is to use another function to track fulfillment (there is likely a module on npm that makes this east, but here is a hand rolled version):
```js
var wait = 1 // at least a close event
function done(){
  res.status(200).end()
}
form.on('part', async function(part) {
  wait++
  await s3Response = s3.upload({Bucket: BUCKET_NAME, Key: key, Body: part}).promise();
  if (!--wait) done()
});

form.on('close', function() {
  if (!--wait) done()
});
```

**Comment by msageryd** [comment]
Thank you Doug. Easier solved than I had thought.

**Comment by dougwilson** [comment]
Hi @msageryd no problem. I didn't realize there was the other issue at first, as between our last interaction and this one, I was out and wasn't responding on GitHub, so while we were talking, I just just checking what other things were in the queue for this module :)
