### ISSUE TITLE
Feature suggestion: Allow async handling in the onPart event without prematurely responding 200 to client

### ISSUE THREAD

**Issue by msageryd** [pillarjs/multiparty#224]
**What**
It would be great if there was a callback param in the event function for "onPart". This function should be called when the part is completely processed.

When all parts are processed, a new event will be called.

**Why**
If anything needs to be awaited inside of the onPart event, there seems to be no secure place to send a 200 response to the client.

I want to send a 200 response only when all parts are completely processed. As of now I don't think there is any way of knowing when all parts are processed.

**Example**
I'm parsing incoming emails from Sendgrid. Before deciding if I want to process an attached file (i.e. save to S3) I need to know the file type. To get the file type I'm using the library `file-type`. I need to await the answer from file-type before I can move on and send the file to S3.

While I'm awaiting the file type, multiparty might decide that all parts has been parsed and emit the onClose event. If I'd put my 200 response in the onClose event I'd send 200 to the client before I've processed the file.

**Possible solution in user-land**
I can be sure that the onPart event will be called for each part before onClose is called. The only problem is when something async happens in onPart (for example awaiting file-type). All lines of code before the first async code in onPart will certainly be called before onClose, so I could define a part-counter-promise which will be resolved when parsedPartCount===processedPartCount. This promise would be scoped so it's visible from both onPart and onClose.

I will await this part counter promise in the onClose event. When it gets resolved I will send 200, if it's rejected I'll send 500.

**Questions**
Would this be a usable concept in this library?
Otherwise, would my user-land workaround solve the problem, or am I thinking wrongly?

**Example code, using the api for this new feature**
```
form.on('part', async function(part, done) {
  //do sync stuff
 filenames.push(part.filename);

  //and also async stuff..
  await asyncStuff(part);

  //call the callback function to let multiparty know that this parsed part has been completely processed
  return done();
}

form.on('finish', async function() {
  //This event will be called when the total number of parsed parts matches the number of done()-calls
  return res.status(200).end();
});
```

**Comment by dougwilson** [comment]
I think the biggest blocker to your proposal is that you are asking for how the on method works to be changed to handle async function. This API is provided by the Node.js version you are using (https://nodejs.org/dist/latest-v13.x/docs/api/events.html#events_emitter_on_eventname_listener) and changes to those would be a Node.js feature request.

**Comment by dougwilson** [comment]
Actually it looks like Node.js does provide a class method to use async await in event listeners: https://nodejs.org/dist/latest-v13.x/docs/api/events.html#events_events_on_emitter_eventname

**Comment by msageryd** [comment]
I’m not following you. Do you mean that the listener function cannot have more than one parameter?

My suggestion has nothing to do with the async keyword. I assume that some older node versions won’t handle async/await in on-functions. But async code can happen without the await keyword.

**Comment by dougwilson** [comment]
Maybe I'm not following you either :) of course this module emits events inside of another event emitter. If your suggestion is to provide a callback function to our emitted event... well, then the Node.js stream events would also need to do that too, otherwise they will keep firing off under this module.

**Comment by msageryd** [comment]
I’m sorry for beimg unclear.

Are you with me regarding the actual problem?
- If I do anything async inside of the onPart event, multipart will emit an onClose event possibly before my async stuff is ready.

**Comment by dougwilson** [comment]
To summarize: it sounds like you are asking if the events from this module can allow async activity before the next one fires, perhaps by providing a callback function as one of the event parameters. This is because the event listeners basically only allow sync behavior.

The answer is more that this module is built on top of the Node.js event emitter that is the http request, and their events (data) do not provide a callback function as a parameter, so I'm not sure what good it would do if the events cannot be stopped below the module using that. As long as the events are coming from the underlying event emitter (Node.js httl request) this module would have to process them (which in turn creates events on thia module's interface).

Perhaps it would help better if you could put together a pull request with what you are looking to achieve?

**Comment by msageryd** [comment]
I’ll try to tinker with this next week.

The callback wouldn’t have anything to do with nodes event handling. The only thing the callback should do is to increase an internal counter in multiparty. This counter would be compared to te actual part count before multiparty emits an onFinish event.

This would ensure that onFinish is only called when all parts are completely processed..

**Comment by dougwilson** [comment]
Interesting. That sounds like a non backwards compatible change, though, to how our events work, and something you can easily do in userland. Simply waiting for all the events to fire before doing something is trivial to do in userland, so it would not be desired to add complexity to an already very complex module to do something already possible...

**Comment by msageryd** [comment]
Your reply on #223 is aproximately what I had in mind, only a little more integrated into multiparty. 

When I saw your code I realized that it’s quite simple. Maybe it’s best to keep this in user-land anyway..
