### ISSUE TITLE
TypeScript version of multiparty

### ISSUE THREAD

**Issue by KostyaTretyak** [pillarjs/multiparty#227]
Hi. First of all, thank you for this wonderful module. Comparing the source code of this module with the module code `formidable` and `bosboy`, your work is much more accurate.

I rewrote the code of this module in TypeScript,
so I invite all TypeScript fans to try [@ts-stack/multiparty](https://github.com/ts-stack/multiparty).

I tried not to change the logic of the native module at all, but thanks to TypeScript, intellisense of your editor greatly simplifies work with this module.

**Comment by dougwilson** [comment]
Hi @KostyaTretyak , thank you so much for sharing!
