### ISSUE TITLE
`for await ... of ...` never end after upgrade NodeJS to 12.18.3

### ISSUE THREAD

**Issue by Mar-Ser** [pillarjs/multiparty#231]
Duplicate of https://github.com/nodejs/node/issues/35190

* **Version**:
** 12.16.0
** ...
** 12.18.3
* **Platform**:
** Windows 10 64
* **Subsystem (with and without it)**:
** Docker node:12.16.0-alpine
** ...
** Docker node:12.18.3-alpine

### What steps will reproduce the bug?

index.js
```
var multiparty = require('multiparty'); // 4.2.2
var http = require('http');
var util = require('util');

http.createServer(async function(req, res) {
  if (req.url === '/upload' && req.method === 'POST') {
    const stream = await getFile(req);

    try {
      console.log(1);
      for await (const data of stream) {
        console.log(2);
        throw new Error('1');
      }
      console.log(3);
    } catch(err) {
      console.log(4, err);
    }

    console.log(5);
    return;
  }

  // show a file upload form
  res.writeHead(200, { 'content-type': 'text/html' });
  res.end(
    '<form action="/upload" enctype="multipart/form-data" method="post">'+
    '<input type="text" name="title"><br>'+
    '<input type="file" name="upload" multiple="multiple"><br>'+
    '<input type="submit" value="Upload">'+
    '</form>'
  );
}).listen(8080);


function getFile(req) {
  return new Promise((resolve) => {
    const form = new multiparty.Form();

    form.on('part', (part) => {
      if (!part.filename) {
        part.resume();
        return;
      }
      resolve(part);
    });

    form.parse(req);
  });
}
```

1. `npm i multiparty@4.2.2`
2. node index.js
3. Go to `localhost:8080`
4. Download any file

### How often does it reproduce? Is there a required condition?

Always in this case

#### v12.14.0 and v12.15.0:
Will print to terminal
```
1
2
4 Error: 1
5
```

#### v12.16.0 ... v12.18.3 (Actual):
```
1
2
```
And looks like it will never end.

### Additional information

I believe this is a Nodejs issue because the compatibility was broken and I could not found the cause of this bug in JS code (include `multiparty` and nodejs js modules). But anyway, take a look. Perhaps I wrong, and the issue in `multiparty` library.

**Comment by dougwilson** [comment]
Thank you, I will take a look. It looks like in 12.16.0 there were a bunch of changes around async iteration on event emitters, which could have introduced this change of behavior. In your example above, you are actually iterating over a built-in Node.js event emitter: a Passthrough stream.

**Comment by dougwilson** [comment]
Taking a look into it, I'm not able to reproduce with 2.18.3. When copying and pasting your exact program and following the instructions on 12.18.3, this is my console output:
```
$ node -v
v12.18.3

$ node index.js
1
2
4 Error: 1
    at Server.<anonymous> (C:\Users\dougw\GitHub\multiparty-231\index.js:13:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
5
```

**Comment by Mar-Ser** [comment]
This is my 
![изображение](https://user-images.githubusercontent.com/32942573/93114292-19323d80-f6c3-11ea-9ff4-2223519f5171.png)

**Comment by dougwilson** [comment]
Strange. I tried with various Node.js versions and all of them show all the numbers. Without the ability to reproduce the issue, there is nothing I can debug. Can you try following your steps above on a different machine just to see if it reproduces or not so we can narrow down which of our machines is the outlier?

**Comment by Mar-Ser** [comment]
This is not related to my machine because in first time it was failed on CI... We (I and my colleague) spent a day trying to debug it. So, it already was reproduced in three different environments...

**Comment by Mar-Ser** [comment]
Anyway, I will try to run this code on my home machine.

**Comment by dougwilson** [comment]
Hm, strange. After I sent that I tried on a laptop, which has never even had Node.js on it before, and worked just fine. Perhaps the issue is within some steps not provided above. I tried with Chrome and the file I uploaded was the index.js file itself. If you upload the index.js file through Chrome with the server, does it still happen?

**Comment by Mar-Ser** [comment]
On home PC a result is the same:
```

$ node -v
v12.18.3


$ node index.js
1
2
```

Also, I tried to upload the index.js itself. And in all cases, I used Chrome, exclude CI.

**Comment by dougwilson** [comment]
Strange. There has to be something different between our methods... 🤔 . Maybe we need to wait for another member to come by and see if they can reproduce and debug through it. You're also always welcome to make a pull request if you can determine the issue, or even add this as a test to our test suite and open a PR with that added (it doesn't matter if it fails, etc.: it'll be a clean environment that gives us both a place to see it).

**Comment by dougwilson** [comment]
Here is another thing to try: I was going to make a reproduction with the PassThrough stream without multiparty, to determine if it was a Node.js issue or multiparty, but since I couldn't reproduce the issue, I am not able to verify if this demonstrates it or not as a reduced test case. Does this experience issues on your setup?
```js
var stream = require('stream');

const pts = new stream.PassThrough();

const run = async () => {
  try {
    console.log(1);
    for await (const data of pts) {
      console.log(2);
      throw new Error('1');
    }
    console.log(3);
  } catch(err) {
    console.log(4, err);
  }

  console.log(5);
};

pts.write('test1');

run()
.then(() => { console.log('done!'); })
.catch((e) => { console.error(e); });
```

**Comment by Mar-Ser** [comment]
No. This code passed.

**Comment by dougwilson** [comment]
Darn. So can you make a pull request to add this issue to our test suite to get it reproducing on our CI?

**Comment by Mar-Ser** [comment]
Ok!

**Comment by Mar-Ser** [comment]
Pipeline for 12.18.3 failed as expected by timeout. 10 and 14 passed. The old versions don't support `for await`.

**Comment by Mar-Ser** [comment]
Our thoughts:
After `throw` or `break`, it exits from the `for await` circle. But before exit, it tries to destroy the stream and waits until it happens. But something is going wrong, and it is never happening...

**Comment by dougwilson** [comment]
Yea, I agree. It seems to be getting stuck in the `return()` of the async iterater for some reason I'm trying to determine.

**Comment by dougwilson** [comment]
Hi @Mar-Ser I know this is an old issue, but I was able to track this down to a regression from the following commit in Node.js: https://github.com/nodejs/node/commit/369b7c235f7e6c6d8737812b4d6c8bd80b08353c . This affects the async await function on streams in general. It seems to behave differently based on internal timings of events within Node.js, which is why it sometimes works, but mostly does not work. The good news is that it seems to not affect Node.js 13+, even this it is landed there. It was backported to Node.js 12.16.0 and likely is conflicting with some other behavior that is in Node.js 12 that is not in 13. Unfortunately it does not seem there is any possible way to fix it from this module.

**Comment by Mar-Ser** [comment]
@dougwilson Thank you!
