### ISSUE TITLE
Listen for close event on part

### ISSUE THREAD

**Issue by thetutlage** [pillarjs/multiparty#235]
Given the scenario, I am manually handling the parts using the `on('part')` event. I validate the stream size as I am consuming it and in case the size exceeds a given limit, I emit the error on stream itself. 

```ts
form.on('part', (part) => {
  part.on('data', () => {
     // write to the write stream
     if (validationFailed) {
        part.emit('error', new Error('validation failure'))
     }
  })
})
```

The write stream ends itself by listening the `error` event on the read stream. All good so far.

But now, the `end` event is never emitted (as per node.js docs) and hence the form is still waiting for this stream to end.

**Comment by dougwilson** [comment]
Hi @thetutlage thanks for the report. Unfortunately if you do this, the `'close'` event is not emitted, either. I'm sure you can edit the source code of this module to verify for this as well. You ideally should not be emitting events on objects that you are not the owner of -- instead you should just be listening to events. If you need to coordinate error handing, I'm sure you can determine an alternative method.
