### ISSUE TITLE
No onField if there are no parts?

### ISSUE THREAD

**Issue by msageryd** [pillarjs/multiparty#239]
I'm parsing inbound emails with multiparty.

If there are no attached files, i.e. no file-parts, `onClose` will be called before `onField`. I would like to reply to the sender with a reminder to attach the files as instructed. Byt I don't know the sender because `onField` is not fired on time.

Is this intentional?
Could I solve this by using `autoFields`?
I don't want to use `autoFiles` because I don't want files on disk.

**Comment by dougwilson** [comment]
Hi @msageryd sorry you are having trouble. All the events like part, field, and file, should be emitted before the close event is emitted. Can you provide a way to reproduce the issue you are seeing? We can help diagnose what is going on and if it's a bug, help to work on a fix.

**Comment by msageryd** [comment]
Thanks Doug.
Yeah, I see that now. I'm zooming in on my problem. 

The problem is that my onField function is async. When I get the `envelope` field I peel out the recipient addresses and await a lookup in my database. While awaiting this, the onClose is called.

Either this is a bad concept (to await inside of events), or there might be a solution?

Possible solution:
Would it be viable to just use a "promise-flag" which I resolve awaiting my lookup? I could await this flag in onClose before doing more work.

**Comment by dougwilson** [comment]
Hi @msageryd it sounds like you may just be new to events in Node.js in general. In Node.js, the event system unfortunately does not support async listeners. Instead it requires you to add your own coordination layer in your code if you want to do something if _both_ event X happened and process Y completed. Just reacting on event X does not guarantee process Y completed by itself.

You can learn more about the Node.js events system here: https://nodejs.org/dist/latest-v14.x/docs/api/events.html

Here is a very simple self-rolled coordination method:
```js
var called = 0

thing.on('eventA', function (obj) {
  process(ob).then(function () {
    if (called++) finish()
  })
})

thing.on('eventB', function (obj) {
   if (called++) finish()
})
```

**Comment by msageryd** [comment]
Thanks a bunch.
I'll read up on this.

**Comment by msageryd** [comment]
Well well.
A year went by and I forgot all of this, too much going on in my small head. Thank you for your patience!

While implementing the counter-concept as you suggests above I recalled doing something similar before. It turns out that I did exactly that. *Facepalm*

https://github.com/pillarjs/multiparty/issues/223

Anyway: It works like a charm.
Closing this.
