### ISSUE TITLE
Unable to detect part correctly if content-disposition name or filename headers do not contain double-quotes.

### ISSUE THREAD

**Issue by surjyams** [pillarjs/multiparty#244]
Some servers send multipart data without enclosing in double quotes the values for, name and filename in the content-disposition part header. This causes the regex to correctly identify such parts. For example, if the content-disposition header for a certain part is as following:
`content-disposition multipart/form-data; name=fieldName` OR
`content-disposition multipart/form-data; name=file; filename=myfile.txt`

In these cases, parser is unable to identify such parts or filenames correctly.

**Comment by dougwilson** [comment]
Hello, and thank you for the report. This is indeed a bug.

**Comment by surjyams** [comment]
@dougwilson Thanks a lot for fixing this !!!
Do you have any tentative dates, when this fix will get released?

**Comment by dougwilson** [comment]
Sorry it slipped off my mind. It has been published as version 4.2.3

**Comment by surjyams** [comment]
Thanks a lot @dougwilson !!!
