### ISSUE TITLE
About Security Issue

### ISSUE THREAD

**Issue by harunoz** [pillarjs/multiparty#246]
Hello,

I have discovered a security issue in multiparty and submit my report to here [here](https://www.huntr.dev/bounties/bc6e0b00-b36d-411b-a58c-4373dac82dcd/). Can you please and check this security issue?

Thank you.

**Comment by dougwilson** [comment]
Hello, and thank you. When I click that link it says I do not have access. Please email me the detials and contents of the report so I can take a look, thank you.

**Comment by dougwilson** [comment]
You can find the emails addresses of a module's owner(s) though npm like any npm module: `npm owner ls multiparty`. You can also find them in package.json files, etc. It should also be on my github profile if you are logged in. Let me know if you still have trouble.
