### ISSUE TITLE
Content type does not support application/json

### ISSUE THREAD

**Issue by gaoshunpeng** [pillarjs/multiparty#251]
### I sent a request. The request header is defined as follows：
```javascript
headers: {
    'content-type': 'application/json'
}
```
### But the library prompts me "unsupported content type at Form. parse". So I looked at the source code，there is such a context related code：
```javascript
var CONTENT_TYPE_RE = /^multipart\/(?:form-data|related)(?:;|$)/i;

var m = CONTENT_TYPE_RE.exec(contentType);
if (!m) {
  validationError(createError(415, 'unsupported content-type'));
  return;
}
```
### It seems that "application/json" is not matched by the rules the defined

**Comment by dougwilson** [comment]
Hello, that is correct, this module does not support `application/json`. This module only does the first line in the readme:

> Parse http requests with content-type `multipart/form-data`, also known as file uploads.
