### ISSUE TITLE
Unicode filenames need to be decoded.

### ISSUE THREAD

**Issue by JakeCigar** [pillarjs/multiparty#252]
Chrome and Firefox "entity encode" unicode file names. Safari does not.

Chrome:"J&amp;#923;&amp;#778;KE_2023-02-25T16:44:24.129Z.avif"
Safari: "JΛ̊KE_2023-02-25T16:44:24.129Z.avif"

( I had to change & to "& amp ;" on the Chrome file name to show  the problem)

My workaround is:
```
form.on("file",(_,file)=>file.originalFilename=parseHtmlEntities(file.originalFilename));
```

```
function parseHtmlEntities(str) {
    return str
        .replace(/&#([0-9]{1,5});/g,     (m,d)=>String.fromCharCode( parseInt(d,10)))
}
```

**Comment by dougwilson** [comment]
Thank you for reporting this. There is an entity decoder there already, but it requires the digits to be exactly 4. I have changed it to be 1-5 like your example as that is what those web browsers are doing and 5 digits contains any character code point.
