### ISSUE TITLE
Error: Expected CR Received 45

### ISSUE THREAD

**Issue by btmdave** [pillarjs/multiparty#35]
Hello,

I'm using express 3.4.6 which uses connect 2.11.2, which uses node-multiparty :)

When I enable the multipart connect module `app.use(express.multipart());` and attempt to do multipart form uploads, multiparty gives me the error `Error: Expected CR Received 45` in all instances.  Any idea what could be the cause of this?

Thanks!

**Comment by williamd5** [comment]
Hello there! I believe I have the same issue.
```sh
curl localhost:80/test -H 'Content-Type: multipart/form-data; boundary=XXX' --data-binary '--XXX
Content-Disposition: form-data; name="name"

John
--XXX
Content-Disposition: form-data; name="age"

12
--XXX--'
```
throws
```
> BadRequestError: Expected CR Received 10
>     at Form._write (/home/user/Projects/core/node_modules/multiparty/index.js:259:49)
>     at writeOrBuffer (node:internal/streams/writable:392:12)
>     at _write (node:internal/streams/writable:333:10)
>     at Writable.write (node:internal/streams/writable:337:10)
>     at IncomingMessage.ondata (node:internal/streams/readable:766:22)
>     at IncomingMessage.emit (node:events:513:28)
>     at Readable.read (node:internal/streams/readable:539:10)
>     at flow (node:internal/streams/readable:1023:34)
>     at resume_ (node:internal/streams/readable:1004:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
https://github.com/pillarjs/multiparty/blob/cb2421fcaca7e28675a3ed964d4418b3bb56e4d7/index.js#L259

Payload from `nc -l 80`
```
POST /test HTTP/1.1
Host: localhost
User-Agent: curl/7.81.0
Accept: */*
Content-Type: multipart/form-data; boundary=XXX
Content-Length: 116

--XXX
Content-Disposition: form-data; name="name"

John
--XXX
Content-Disposition: form-data; name="age"

12
--XXX--
```

**Comment by williamd5** [comment]
> @williamd5 you have a different error messge. You message and example indicates you are terminating your multipart lines with only the LF characher when you need to use CR and LF between lines just like in HTTP. If you are planning to manually construct a multipart body by hand, make sure to read over the spec at https://www.rfc-editor.org/rfc/rfc2046#section-5.1

Thank you. I copy-pasted the data and was unaware what CF/LF were and my computer probably changed the new line characters when copy/pasting.
I copied the data as base64 and sent the request using `echo 'base64data...' | base64 --decode | nc localhost 80` and that worked,
