### ISSUE TITLE
How to get to the file data

### ISSUE THREAD

**Issue by toddhickerson** [pillarjs/multiparty#6]
Thanks for your great work on node-multiparty (and of course, formidable). Question for you….

In this example: https://github.com/superjoe30/node-multiparty/blob/master/examples/upload.js

…I can see how to get all the metadata about the file, but how do you actually get at the contents of the file?

My goal is to read the bits (small images) and save them into MongoDB. They are well under 4MB, so no need for GridFS.

Would appreciate a sample code snippet or an expanded example on how to actually read the bytes into a variable.

**Comment by vipersec** [comment]
Excuse me but in which variable exactly is this `readable stream` you are talking about?
Can I get it before the form parsing is completed?
