### ISSUE TITLE
Phusion Passenger Error: stream ended unexpectedly

### ISSUE THREAD

**Issue by bjedrocha** [pillarjs/multiparty#68]
Hi there,

We have intermittent file upload failures and the only error message we're seeing in the logs is `Error: stream ended unexpectedly` followed by a stack trace. The stack trace points to the following code within multiparty

``` js
self.on('finish', function() {
    if ((self.state === HEADER_FIELD_START && self.index === 0) ||
        (self.state === PART_DATA && self.index === self.boundary.length))
    {
      self.onParsePartEnd();
    } else if (self.state !== END) {
      self.handleError(new Error('stream ended unexpectedly'));
    }
    self.finished = true;
    maybeClose(self);
  });
```

In our case in particular, the error is thrown when `state = PART_DATA`, `index = 0`, and `boundary.length = 42`. On successful uploads, the state equals `END`. I'm trying to figure out how the index is calculated and under what circumstances this function will be called when the state is equal to `PART_DATA`?

As a test, I removed the `self.index === self.boundary.length` check from the if statement and this fixed my issue but obviously that check is there for a reason.

I should also note that this Node application is running under Nginx + Passenger (with SSL) and these errors are only noticed when the upload is initiated from a Chrome browser ( boundary is `------WebKitFormBoundary1ONhqXuetuF7yDxs` ).

Any help would be greatly appreciated. Thanks.

**Comment by dtytomi** [comment]
@FooBarWidget please is there any example of how you solved this problem that I can follow.

**Comment by FooBarWidget** [comment]
@dtytomi Just use the latest Passenger version.

**Comment by dtytomi** [comment]
@FooBarWidget am using node and express for mean stack app, but passenger is for ruby and python application. Please do you have another alternative that works in meanjs app environment. Thanks

**Comment by dtytomi** [comment]
This is the link to the question I asked on stackoverflow, showing a  preview of my code http://stackoverflow.com/questions/33596469/error-stream-ended-unexpectedly

**Comment by tunylund** [comment]
Can't speak for FooBarWidget, but for what it's worth, we're using passenger with nginx for both rails and node.js apps and it works wonderfully.

**Comment by johnmanoahs** [comment]
I was able to solve the torturous *"stream ended unexpectedly"* error after hours and hours of debugging. The error magically vanished after I commented out **app.use(fileUpload());** from my node server page. Not sure why but it works.
