### ISSUE TITLE
File size from stream

### ISSUE THREAD

**Issue by jsilvestre** [pillarjs/multiparty#70]
Hello and thank your work, it's going to be very helpful!

I find difficulties understanding what "part.byteCount" is since it changes in function of the part orders. I get the correct file size if the file is the last part (as stated in the documentation) but I don't understand why it's not the correct file size if it's not the case; and can't figure how to compute it if it's not the last part (and the part doesn't have a content-length header).

Thanks in advance for your answer.
Cheers!

**Comment by caub** [comment]
```byteCount - assuming that this is the last part in the request, this is the size of this part in bytes. You could use this, for example, to set the Content-Length header if uploading to S3. If the part had a Content-Length header then that value is used here instead.`
```
so if I send 3 files 5kb 30kb 20kb, it seems the first part.byCount is 55kB (total), the second is 50kb and last is 20kb

so if I need to know the size of a part, I can know it from the next one (or close when it's the last one) right?
